// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account.proto

#include "account.pb.h"
#include "account.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* AccountService_method_names[] = {
  "/AccountService/GetAllAccount",
};

std::unique_ptr< AccountService::Stub> AccountService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AccountService::Stub> stub(new AccountService::Stub(channel, options));
  return stub;
}

AccountService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetAllAccount_(AccountService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AccountService::Stub::GetAllAccount(::grpc::ClientContext* context, const ::Request& request, ::GetAllAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Request, ::GetAllAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllAccount_, context, request, response);
}

void AccountService::Stub::async::GetAllAccount(::grpc::ClientContext* context, const ::Request* request, ::GetAllAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Request, ::GetAllAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllAccount_, context, request, response, std::move(f));
}

void AccountService::Stub::async::GetAllAccount(::grpc::ClientContext* context, const ::Request* request, ::GetAllAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetAllAccountResponse>* AccountService::Stub::PrepareAsyncGetAllAccountRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetAllAccountResponse, ::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetAllAccountResponse>* AccountService::Stub::AsyncGetAllAccountRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

AccountService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::Request, ::GetAllAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Request* req,
             ::GetAllAccountResponse* resp) {
               return service->GetAllAccount(ctx, req, resp);
             }, this)));
}

AccountService::Service::~Service() {
}

::grpc::Status AccountService::Service::GetAllAccount(::grpc::ServerContext* context, const ::Request* request, ::GetAllAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


